Replaced hardcoded echo's with modular functions

diff --git a/scripts/BackUp_Config_files b/scripts/BackUp_Config_files
--- a/scripts/BackUp_Config_files
+++ b/scripts/BackUp_Config_files
@@ -1,61 +1,211 @@
 #!/bin/bash
 
-FLAG1="$1"
-
-GIT_DIR="$HOME/DEV_DIR/GIT/ConfigFiles"
-SCRIPTS="$HOME/.bin"
+set -euo pipefail
+IFS=$'\n\t'
 
 # colors
-highlight="\033[1m"
-green="\033[38;2;100;255;40m"
-blue="\033[38;2;100;100;240m"
-red="\033[38;2;255;10;10m"
-no_col="\033[0m"
+GREEN="\033[38;2;100;255;40m"
+YELLOW="\033[38;2;255;190;65m"
+BLUE="\033[38;2;100;100;240m"
+RED="\033[38;2;255;10;10m"
+NC="\033[0m"
+HL="\033[1m"
 
-function Copy() {
-    cp -r $HOME/.config/hypr/* "$GIT_DIR/hyprland_config/" && \
-        echo -e "Copied '${green}$HOME/.config/hypr/${no_col}*' ${red}--->${no_col} '${blue}$GIT_DIR/hyprland_config/'${no_col}"
+# An array to hold all the given flags
+FLAGS_ARRAY=("$@")
 
-    cp $HOME/.vimrc.bak "$GIT_DIR/vim_config/vimrc" && \
-        echo -e "Copied '${green}$HOME/.vimrc.bak${no_col}' ${red}--->${no_col} '${blue}$GIT_DIR/vim_config/vimrc${no_col}'"
+# Your git local dotfile repository
+GIT_DIR="${HOME}/DEV_DIR/GIT/ConfigFiles"
 
-    cp $HOME/.config/nvim/init.vim.bak "$GIT_DIR/neovim_config/init.vim" && \
-        echo -e "Copied '${green}$HOME/.config/nvim/init.vim.bak${no_col}' ${red}--->${no_col} '${blue}$GIT_DIR/neovim_config/init.vim${no_col}'"
+# 1 for git status 0 for no git status
+GIT_STATUS=0
 
-    cp $HOME/.SHELL_RC "$GIT_DIR/shell_config/SHELL_RC" && \
-        echo -e "Copied '${green}$HOME/.SHELL_RC${no_col}' ${red}--->${no_col} '${blue}$GIT_DIR/shell_config/SHELL_RC${no_col}'"
+# LOG=2 INFO=1 ERROR=0
+LOG_LEVEL=0
 
-    cp $HOME/.bashrc "$GIT_DIR/shell_config/bashrc" && \
-        echo -e "Copied '${green}$HOME/.bashrc${no_col}' ${red}--->${no_col} '${blue}$GIT_DIR/shell_config/bashrc${no_col}'"
+# command in use to copy stuff
+SYNC_="rsync"
 
-    cp $HOME/.config/foot/foot.ini "$GIT_DIR/sway_config/foot/" && \
-        echo -e "Copied '${green}$HOME/.config/foot/foot.ini${no_col}' ${red}--->${no_col} '${blue}$GIT_DIR/sway_config/foot/${no_col}'"
-
-    cp -r $HOME/.config/sway/* "$GIT_DIR/sway_config/" && \
-        echo -e "Copied '${green}$HOME/.config/sway/${no_col}*' ${red}--->${no_col} '${blue}$GIT_DIR/sway_config/${no_col}'"
-
-    cp -r $HOME/.config/i3/* "$GIT_DIR/i3_config/" && \
-        echo -e "Copied '${green}$HOME/.config/i3/${no_col}*' ${red}--->${no_col} '${blue}$GIT_DIR/i3_config/${no_col}'"
-
-    cp -r $HOME/.config/waybar/* "$GIT_DIR/waybar_config/" && \
-        echo -e "Copied '${green}$HOME/.config/waybar/${no_col}*' ${red}--->${no_col} '${blue}$GIT_DIR/waybar_config/${no_col}'"
-
-    cp -r $HOME/.config/wofi/* "$GIT_DIR/wofi_config/" && \
-        echo -e "Copied '${green}$HOME/.config/wofi/${no_col}*' ${red}--->${no_col} '${blue}$GIT_DIR/wofi_config/${no_col}'"
-
-    cp -r $SCRIPTS/* $GIT_DIR/scripts/ && \
-        echo -e "Copied '${green}$SCRIPTS/${no_col}*' ${red}--->${no_col} '${blue}$GIT_DIR/scripts${no_col}'"
+function ERROR() {
+    local msg="${2:-""}"
+    [[ $LOG_LEVEL -ge 0 ]] && {
+        echo -e "[${HL}${RED}ERROR${NC}]: ${msg}$1"
+    } || {
+        return 0
+    }
 }
 
-if [[ ! -d "$GIT_DIR" ]]; then
-    echo "Given Directory doesn't exits '$GIT_DIR'"
-    exit 1
+function INFO() {
+    local msg="${2:-""}"
+    [[ $LOG_LEVEL -ge 1 ]] && {
+        echo -e "[${HL}${GREEN}INFO${NC}]: ${msg}$1"
+    } || {
+        return 0
+    }
+}
+
+function DEBUG_LOG() {
+    local msg="${2:-""}"
+    [[ $LOG_LEVEL -ge 2 ]] && {
+        echo -e "[${HL}${YELLOW}DEBUG_LOG${NC}]: ${msg}$1"
+    } || {
+        return 0
+    }
+}
+
+function CopyFiles() {
+    local SOURCE="$1"
+    local DEST="$2"
+
+    if [[ ! -f "${SOURCE}" ]]; then
+        ERROR "Source '${BLUE}${SOURCE}${NC}' file does not exist"
+        return 1
+    fi
+
+    mkdir --parents -- $(dirname "${DEST}")
+
+    if [[ $LOG_LEVEL -ge 2 ]]; then
+        if [[ "$SYNC_" == "rsync" ]]; then
+            $SYNC_ --progress --archive "${SOURCE}" "${DEST}" || ERROR "Copy failed"
+            INFO "Copied '${GREEN}${SOURCE}${NC}' ${RED}--->${NC} '${BLUE}${DEST}${NC}'"
+        else
+            $SYNC_ --verbose "${SOURCE}" "${DEST}" || ERROR "Copy failed"
+            INFO "Copied '${GREEN}${SOURCE}${NC}' ${RED}--->${NC} '${BLUE}${DEST}${NC}'"
+        fi
+    else
+        if [[ "$SYNC_" == "rsync" ]]; then
+            $SYNC_ --archive "${SOURCE}" "${DEST}" 1> /dev/null 2>&1 || ERROR "Copy failed"
+            INFO "Copied '${GREEN}${SOURCE}${NC}' ${RED}--->${NC} '${BLUE}${DEST}${NC}'"
+        else
+            $SYNC_ "${SOURCE}" "${DEST}" 1> /dev/null 2>&1 || ERROR "Copy failed"
+            INFO "Copied '${GREEN}${SOURCE}${NC}' ${RED}--->${NC} '${BLUE}${DEST}${NC}'"
+        fi
+    fi
+}
+
+function CopyDirs() {
+    local SOURCE="$1"
+    local DEST="$2"
+
+    if [[ ! -d "${SOURCE}" ]]; then
+        ERROR "Source '${BLUE}${SOURCE}${NC}' directory does not exist"
+        return 1
+    fi
+
+    mkdir --parents -- "${DEST}"
+
+    if [[ $LOG_LEVEL -ge 2 ]]; then
+        if [[ "$SYNC_" == "rsync" ]]; then
+            $SYNC_ --progress --archive "${SOURCE}/" "${DEST}/" || ERROR "Copy failed"
+            INFO "Copied '${GREEN}${SOURCE}${NC}/*' ${RED}--->${NC} '${BLUE}${DEST}${NC}'"
+        else
+            $SYNC_ --verbose --recursive "${SOURCE}"/* "${DEST}" || ERROR "Copy failed"
+            INFO "Copied '${GREEN}${SOURCE}${NC}/*' ${RED}--->${NC} '${BLUE}${DEST}${NC}'"
+        fi
+    else
+        if [[ "$SYNC_" == "rsync" ]]; then
+            $SYNC_ --archive "${SOURCE}/" "${DEST}/" 1> /dev/null 2>&1 || ERROR "Copy failed"
+            INFO "Copied '${GREEN}${SOURCE}${NC}/*' ${RED}--->${NC} '${BLUE}${DEST}${NC}'"
+        else
+            $SYNC_ --recursive "${SOURCE}"/* "${DEST}" 1> /dev/null 2>&1 || ERROR "Copy failed"
+            INFO "Copied '${GREEN}${SOURCE}${NC}/*' ${RED}--->${NC} '${BLUE}${DEST}${NC}'"
+        fi
+    fi
+}
+
+for (( i=0 ; i < ${#FLAGS_ARRAY[@]} ; i++ )); do
+    arg="${FLAGS_ARRAY[$i]}"
+    if [[ "$arg" == -* ]]; then
+        case "$arg" in
+            -v|--verbose|--progress)
+                LOG_LEVEL=1
+                DEBUG_LOG "Verbose is set"
+                ;;
+            -l|--log|--loglevel)
+                unset LOG_LEVEL
+                readonly LOG_LEVEL="${FLAGS_ARRAY[$(( i + 1 ))]:-1}"
+                if [[ -z "$LOG_LEVEL" ]]; then
+                    LOG_LEVEL=1
+                    ERROR "LOG_LEVEL: $LOG_LEVEL" "No LOG_LEVEL given, Defaulting to: "
+                elif [[ "$LOG_LEVEL" -gt 2 ]]; then
+                    DEBUG_LOG "LOG_LEVEL has no effect over integer 2"
+                else
+                    if [[ $LOG_LEVEL -eq 2 ]]; then
+                        DEBUG_LOG "Debugging enabled"
+                    fi
+                    DEBUG_LOG "LOG_LEVEL: $LOG_LEVEL"
+                fi
+                i=$(( i + 1 ))
+                ;;
+            -d|-db|--db|--deb|--debug)
+                LOG_LEVEL=2
+                DEBUG_LOG "Debugging enabled"
+                ;;
+            -g|-gs|--gs|--status|--git-status)
+                GIT_STATUS=1
+                DEBUG_LOG "GIT_STATUS is set"
+                ;;
+            *)
+                ERROR "Invalid flag: $arg"
+                ;;
+        esac
+    fi
+done
+
+if command -v rsync 1> /dev/null 2>&1; then
+    SYNC_="rsync"
+    [[ $? -ne 0 ]] && ERROR "'rsync' not found. Falling back to 'cp'."
+elif command -v cp 1> /dev/null 2>&1; then
+    SYNC_="cp"
 fi
 
-Copy
+# Why local dotfile directory doesn't exist
+if [[ ! -d "${GIT_DIR}" ]]; then
+    mkdir --parents "${GIT_DIR}" || {
+        ERROR "Cannot create '${BLUE}${GIT_DIR}${NC}'"
+        exit 1
+    }
+fi
 
-if [[ $FLAG1 =~ ^(gs|diff|status)$ ]]; then
-    cd $GIT_DIR
+DEBUG_LOG "GIT_DIR=$GIT_DIR"
+DEBUG_LOG "GIT_STATUS=$GIT_STATUS"
+DEBUG_LOG "LOG_LEVEL=$LOG_LEVEL"
+DEBUG_LOG "SYNC_=$SYNC_"
+
+echo && INFO "Dotfile directory: ${BLUE}${GIT_DIR}${NC}\n"
+
+### Files to file Copy
+declare -A FILES_TO_COPY=(
+    ["${HOME}/.vimrc.bak"]="${GIT_DIR}/vim_config/vimrc"
+    ["${HOME}/.config/nvim/init.vim.bak"]="${GIT_DIR}/neovim_config/init.vim"
+    ["${HOME}/.SHELL_RC"]="${GIT_DIR}/shell_config/SHELL_RC"
+    ["${HOME}/.bashrc"]="${GIT_DIR}/shell_config/bashrc"
+    ["${HOME}/.config/foot/foot.ini"]="${GIT_DIR}/sway_config/foot/foot.ini"
+)
+
+# Start copying all the files to the destination
+for src in "${!FILES_TO_COPY[@]}"; do
+    CopyFiles "${src}" "${FILES_TO_COPY[$src]}"
+done
+
+### Directory to Directory Copy
+declare -A DIRS_TO_COPY=(
+    ["${HOME}/.config/hypr"]="${GIT_DIR}/hyprland_config"
+    ["${HOME}/.config/sway"]="${GIT_DIR}/sway_config"
+    ["${HOME}/.config/i3"]="${GIT_DIR}/i3_config"
+    ["${HOME}/.config/waybar"]="${GIT_DIR}/waybar_config"
+    ["${HOME}/.config/wofi"]="${GIT_DIR}/wofi_config"
+    ["${HOME}/.config/qutebrowser"]="${GIT_DIR}/qutebrowser"
+    ["${HOME}/.bin"]="${GIT_DIR}/scripts"
+)
+
+# Start copying directory content to the the destination
+for src in "${!DIRS_TO_COPY[@]}"; do
+    CopyDirs "${src}" "${DIRS_TO_COPY[$src]}"
+done
+
+if [[ ${GIT_STATUS} -eq 1 ]]; then
+    cd ${GIT_DIR}
     git status
 fi
 
diff --git a/scripts/JournalToday b/scripts/JournalToday
--- a/scripts/JournalToday
+++ b/scripts/JournalToday
@@ -1,79 +1,84 @@
 #!/bin/bash
 
-### Set Variables and colors
-Editor="$1"
+### Edit these vairables to their correct values
 
-JournalDir="${HOME}/journalD"
-JournalFile="$(date +%d-%b-%Y_).md"
+### Journal directory (All your journal's will be here)
+JOURNAL_DIR="${HOME}/journalD"
+### tr TRANSFORM_KEY file
+TRANSFORM_KEY_FILE="${HOME}/._tr"
+### Any existing template you want
+TEMPLATE_FILE_PATH="$HOME/.scripts/JR"
+### Line of text after and including from the TEMPLATE_FILE_PATH will be part of journal template
+SELECTED_TEXT="### Today's tasklist and journal"
 
-TransformKeyPath="${HOME}/._tr"
-TransformKey="$(cat ${TransformKeyPath})"
-TemplatePath="$HOME/.scripts/JR"
-green="\033[3;32m"
-no_col="\033[0m"
+EDITOR="$1"
+JOURNAL_FILE="$(date +%d-%b-%Y_).md"
+TRANSFORM_KEY="$(cat $TRANSFORM_KEY_FILE)"
+GREEN="\033[3;32m"
+NC="\033[0m"
 
 function cleanup() {
-    if [[ -f "$TempFile" ]]; then
-        tr 'A-Za-z' "${TransformKey}" < "${TempFile}" > "${JournalDir}/${JournalFile}"
-        rm -f "$TempFile"
+    if [[ -f "$TEMP_FILE" ]]; then
+        tr 'A-Za-z' "$TRANSFORM_KEY" < "$TEMP_FILE" > "$JOURNAL_DIR/$JOURNAL_FILE"
+        rm -f "$TEMP_FILE"
     fi
 }
 
-if [[ ! -d "${JournalDir}" ]]; then
-    echo "Path '"${JournalDir}"' doesnt' exist"
-    if mkdir -p "${JournalDir}"; then
-        echo "Created '${JournalDir}'"
+if [[ ! -d "$JOURNAL_DIR" ]]; then
+    echo "Path '"$JOURNAL_DIR"' doesnt' exist"
+    if mkdir -p "$JOURNAL_DIR"; then
+        echo "Created '$JOURNAL_DIR'"
         sleep 1
     else
-        echo "Failed to create '${JournalDir}'"
+        echo "Failed to create '$JOURNAL_DIR'"
         exit 1
     fi
 fi
 
-[[ -s "${TransformKeyPath}" ]] || {
-    echo "Missing or empty transform key at '${TransformKeyPath}'"
+[[ -s "$TRANSFORM_KEY_FILE" ]] || {
+    echo "Missing or empty transform key at '$TRANSFORM_KEY_FILE'"
     exit 1
 }
 
-### Only run if first arguemnt (The Editor) is given
-if [[ -n "$Editor" ]]; then
+### Only run if first arguemnt (The EDITOR) is given
+if [[ -n "$EDITOR" ]]; then
     ### If given editor does not exists fallback to vim
-    command -v "$Editor" 1> /dev/null 2>&1 || Editor="vim"
+    command -v "$EDITOR" 1> /dev/null 2>&1 || EDITOR="vim"
 
     ### Create a temporary file
-    TempFile="$(mktemp ${JournalDir}/.${JournalFile}.XXXXXXXXXX.tmp)"
-    trap cleanup EXIT INT TERM
+    TEMP_FILE="$(mktemp $JOURNAL_DIR/.$JOURNAL_FILE.XXXXXXXXXX.tmp)"
+    trap cleanup EXIT INT TERM KILL
 
     ### If file doesn't exist and empty, create the file and provide a default template
-    if [[ ! -s "${JournalDir}/${JournalFile}" ]]; then
+    if [[ ! -s "$JOURNAL_DIR/$JOURNAL_FILE" ]]; then
 
         ### Fill the Journal with a template
-        grep -A 100 "### Today's tasklist and journal" "${TemplatePath}" 1> "${JournalDir}/${JournalFile}"
+        grep -A 100 "$SELECTED_TEXT" "$TEMPLATE_FILE_PATH" 1> "$JOURNAL_DIR/$JOURNAL_FILE"
 
-        tr 'A-Za-z' "${TransformKey}" < "${JournalDir}/${JournalFile}" > "${TempFile}"
-        mv "${TempFile}" "${JournalDir}/${JournalFile}"
+        tr 'A-Za-z' "$TRANSFORM_KEY" < "$JOURNAL_DIR/$JOURNAL_FILE" > "$TEMP_FILE"
+        mv "$TEMP_FILE" "$JOURNAL_DIR/$JOURNAL_FILE"
     fi
 
-    if [[ "$Editor" == "vim" ]]; then
-        tr "${TransformKey}" 'A-Za-z' < "${JournalDir}/${JournalFile}" > "${TempFile}"
+    if [[ "$EDITOR" == "vim" ]]; then
+        tr "$TRANSFORM_KEY" 'A-Za-z' < "$JOURNAL_DIR/$JOURNAL_FILE" > "$TEMP_FILE"
         sleep 0.01
-        vim -c 'colorscheme unokai' "${TempFile}"
-        tr 'A-Za-z' "${TransformKey}" < "${TempFile}" > "${JournalDir}/${JournalFile}"
-        rm -f "${TempFile}"
+        vim -c 'colorscheme unokai' "$TEMP_FILE"
+        tr 'A-Za-z' "$TRANSFORM_KEY" < "$TEMP_FILE" > "$JOURNAL_DIR/$JOURNAL_FILE"
+        rm -f "$TEMP_FILE"
     else
-        tr "${TransformKey}" 'A-Za-z' < "${JournalDir}/${JournalFile}" > "${TempFile}"
+        tr "$TRANSFORM_KEY" 'A-Za-z' < "$JOURNAL_DIR/$JOURNAL_FILE" > "$TEMP_FILE"
         sleep 0.01
-        "${Editor}" "${TempFile}"
-        tr 'A-Za-z' "${TransformKey}" < "${TempFile}" > "${JournalDir}/${JournalFile}"
-        rm -f "${TempFile}"
+        "$EDITOR" "$TEMP_FILE"
+        tr 'A-Za-z' "$TRANSFORM_KEY" < "$TEMP_FILE" > "$JOURNAL_DIR/$JOURNAL_FILE"
+        rm -f "$TEMP_FILE"
     fi
     exit 0
 fi
 
-if [[ ! -f "${JournalDir}/${JournalFile}" ]]; then
-    touch "${JournalDir}/${JournalFile}"
-    echo -e "Created $green"${JournalDir}/${JournalFile}"$no_col"
+if [[ ! -f "$JOURNAL_DIR/$JOURNAL_FILE" ]]; then
+    touch "$JOURNAL_DIR/$JOURNAL_FILE"
+    echo -e "Created $GREEN"$JOURNAL_DIR/$JOURNAL_FILE"$NC"
 else
-    echo -e "File already exists: $green"${JournalDir}/${JournalFile}"$no_col"
+    echo -e "File already exists: $GREEN"$JOURNAL_DIR/$JOURNAL_FILE"$NC"
 fi
 
diff --git a/scripts/MountSSHFS_filesystem b/scripts/MountSSHFS_filesystem
--- a/scripts/MountSSHFS_filesystem
+++ b/scripts/MountSSHFS_filesystem
@@ -13,8 +13,9 @@ PORT="8022"
 FLAG="$1"
 
 ### Some colors
-LITTLE_BLUE="\033[38;2;126;117;255m"
 LITTEL_RED="\033[38;2;200;10;10m"
+LITTLE_GREEN="\033[38;2;120;200;85m"
+LITTLE_BLUE="\033[38;2;126;117;255m"
 BLUE="\033[38;2;152;60;200m"
 GREEN="\033[38;2;138;230;81m"
 GRAY="\033[38;2;125;125;125m"
@@ -22,14 +23,38 @@ ORANGE="\033[38;2;200;64;38m"
 PERL_GREEN="\033[1m\033[38;2;0;200;160m"
 NC="\033[0m"
 
-### Additional Tweaks
+### SSH specific variables
 CONFIG_FILE="/tmp/.sshfsMountScriptConf"
 PRIVATE_KEY="$HOME/.ssh"
-ENABLE_DEBUGGING="no"
 SSH_OPTIONS="-oreconnect -oCompression=yes"
+
+### Debug and networking variables
+DEBUG=1
+# Ping command will wait till NETWORK_TIMEOUT
 NETWORK_TIMEOUT=3
+# 0 Set's no limit on Mount location 0 > will set the mount location timeout
 MOUNT_TIMEOUT=0
+# Only changes the permissions for local directory created on local machine
 DESTINATION_DIRECTORY_PERMISSION=755
+
+function DEBUG_LOG() {
+    if [[ $DEBUG -eq 1 ]]; then
+        echo -e "[${ORANGE}DEBUG${NC}]: $1"
+    fi
+}
+
+function INFO() {
+    echo -e "[${LITTLE_GREEN}INFO${NC}]: $1"
+}
+
+function ERROR() {
+    echo -e "[${LITTEL_RED}ERROR${NC}]: $1"
+    if [[ $2 -ne 0 ]]; then
+        exit 1
+    else
+        return 0
+    fi
+}
 
 function InstallTool() {
     Tool="$1"
@@ -56,13 +81,13 @@ function InstallTool() {
 function SetTextEditor() {
     if command -v nvim 1> /dev/null 2>&1; then
         EDITOR="nvim"
-        return
+        return 0
     elif command -v vim  1> /dev/null 2>&1; then
         EDITOR="vim"
-        return
+        return 0
     elif command -v nano 1> /dev/null 2>&1; then
         EDITOR="nano"
-        return
+        return 0
     else
         echo "NO text editor found on your system"
         InstallTool "vim"
@@ -71,6 +96,8 @@ function SetTextEditor() {
 
 function Log_Message() {
     showConfig="$1"
+
+    local type="$1"
 
     if [[ "${UseConfig}" =~ ^(No|no)$ ]]; then
         echo -e "#=========================================================================="
@@ -113,7 +140,7 @@ function Log_Message() {
         echo -e "# ${ORANGE}PORT${NC}=\"${PORT}\""
         echo -e "#"
         echo -e "# ${GRAY}### Enable bash script debugging (yes or no)${NC}"
-        echo -e "# ${ORANGE}ENABLE_DEBUGGING${NC}=\"${ENABLE_DEBUGGING}\""
+        echo -e "# ${ORANGE}DEBUG${NC}=\"${DEBUG}\""
         echo -e "#"
         echo -e "# ${GRAY}### Timeout in seconds to wait for the remote host to respond (Network check)${NC}"
         echo -e "# ${ORANGE}NETWORK_TIMEOUT${NC}=${BLUE}${NETWORK_TIMEOUT}${NC}"
@@ -132,11 +159,11 @@ function Log_Message() {
     fi
 
     if [[ "${isunMounted}" -eq 1 ]]; then
-        echo -e "# Successfully unmounted '${LITTLE_BLUE}${DESTINATION}${NC}'"
+        INFO "Successfully unmounted '${LITTLE_BLUE}${DESTINATION}${NC}'"
         [[ ${DestRemoved} -eq 1 ]] && {
-        echo -e "# Removed '${LITTLE_BLUE}${DESTINATION}${NC}'"
+            INFO "Removed '${LITTLE_BLUE}${DESTINATION}${NC}'"
         } || {
-        echo -e "# [${LITTEL_RED}ERROR${NC}]: Failed to Remove '${LITTLE_BLUE}${DESTINATION}${NC}'"
+            ERROR "Failed to Remove '${LITTLE_BLUE}${DESTINATION}${NC}'" 1
         }
         echo ""
     fi
@@ -181,7 +208,7 @@ function EditConfig() {
         echo -e "PORT=\"${PORT}\""                                                                 >> "${CONFIG_FILE}"
         echo -e ""                                                                                 >> "${CONFIG_FILE}"
         echo -e "### Enable bash script debugging (yes or no)"                                     >> "${CONFIG_FILE}"
-        echo -e "ENABLE_DEBUGGING=\"${ENABLE_DEBUGGING}\""                                         >> "${CONFIG_FILE}"
+        echo -e "DEBUG=\"${DEBUG}\""                                         >> "${CONFIG_FILE}"
         echo -e ""                                                                                 >> "${CONFIG_FILE}"
         echo -e "### Additional SSH options (e.g., -oreconnect -oCompression)"                     >> "${CONFIG_FILE}"
         echo -e "SSH_OPTIONS=\"${SSH_OPTIONS}"\"                                                   >> "${CONFIG_FILE}"
@@ -216,17 +243,17 @@ if [[ -s "${CONFIG_FILE}" ]]; then
     if [[ "${UseConfig}" =~ ^(Yes|yes|true)$ ]]; then
         source "${CONFIG_FILE}"
     fi
-    [[ "${ENABLE_DEBUGGING}" =~ ^(Yes|YES|yes|true)$ ]] && {
-        echo -e "DEBUG_MESSAGE: UseConfig=$(grep UseConfig "${CONFIG_FILE}" | cut -d'=' -f'2' | tr -d '"')"
-        echo -e "DEBUG_MESSAGE: export UseConfig\n"
+    [[ "${DEBUG}" -eq 1 ]] && {
+        DEBUG_LOG "UseConfig=$(grep UseConfig "${CONFIG_FILE}" | cut -d'=' -f'2' | tr -d '"')"
+        DEBUG_LOG "export UseConfig\n"
     }
-    [[ "${ENABLE_DEBUGGING}" =~ ^(Yes|YES|yes|true)$ ]] && \
-        echo -e "DEBUG_MESSAGE: source "${CONFIG_FILE}"\n"
+
+    [[ "${DEBUG}" -eq 1 ]] && DEBUG_LOG "source "${CONFIG_FILE}"\n"
 fi
 
 ### If sshfs binary is not installed
-if ! command -v sshfs  1> /dev/null 2>&1; then
-    echo -e "[${LITTEL_RED}ERROR${NC}]: 'sshfs' is not Installed, install it first using your package manager"
+if ! command -v sshfs  &> /dev/null; then
+    ERROR "'${GREEN}sshfs${NC}' is not Installed, install it first using your package manager" 1
     InstallTool "sshfs"
 fi
 
@@ -236,99 +263,87 @@ case "${FLAG}" in
         EditConfig
         ;;
     --debug)
-        ENABLE_DEBUGGING="yes"
+        DEBUG=1
         ;;
 esac
 
 ### Enable bash debugging
-[[ ${ENABLE_DEBUGGING} =~ ^"yes|Yes|YES|true"$ ]] && {
+[[ ${DEBUG} -eq 1 ]] && {
     set -x
 }
 
 ### Destination directory exists? unmount and remove it
 if [[ -d "${DESTINATION}" ]]; then
-    [[ "${ENABLE_DEBUGGING}" =~ ^(Yes|YES|yes|true)$ ]] && \
-        echo -e "DEBUG_MESSAGE: timeout --signal KILL 4 fusermount -u "${DESTINATION}" 1> /dev/null 2>&1\n"
+    [[ "${DEBUG}" -eq 1 ]] && DEBUG_LOG "timeout --signal KILL 4 fusermount -u "${DESTINATION}" 1> /dev/null 2>&1\n"
     timeout --signal KILL 4 fusermount -u "${DESTINATION}" 1> /dev/null 2>&1 && {
         isunMounted=1
     } || {
-        echo -e "[${LITTEL_RED}ERROR${NC}]: Un-mount failed on '${LITTLE_BLUE}${DESTINATION}${NC}'"
+        ERROR "Un-mount failed on '${LITTLE_BLUE}${DESTINATION}${NC}'"
     }
-    [[ "${ENABLE_DEBUGGING}" =~ ^(Yes|YES|yes|true)$ ]] && \
-        echo -e "DEBUG_MESSAGE: rm -rf "${DESTINATION}" && DestRemoved=1\n"
+    [[ "${DEBUG}" -eq 1 ]] && DEBUG_LOG "rm -rf "${DESTINATION}" && DestRemoved=1\n"
     rm -rf "${DESTINATION}" && DestRemoved=1
     Log_Message "noConfig"
     exit 0
 fi
 
 ### Before mounting check if host or IP is alive and listening
-[[ "${ENABLE_DEBUGGING}" =~ ^(Yes|YES|yes|true)$ ]] && \
-    echo -e "DEBUG_MESSAGE: ping -c 1 -W ${NETWORK_TIMEOUT} ${HOSTNAME} 1> /dev/null 2>&1\n"
-ping -c 1 -W ${NETWORK_TIMEOUT} ${HOSTNAME} 1> /dev/null 2>&1 || {
-    echo -e "'${LITTLE_BLUE}${HOSTNAME}${NC}' Not reachable, check the connection."
-    exit 1
+[[ "${DEBUG}" -eq 1 ]] && DEBUG_LOG "ping -c 1 -W ${NETWORK_TIMEOUT} ${HOSTNAME} &> /dev/null\n"
+ping -c 1 -W ${NETWORK_TIMEOUT} ${HOSTNAME} &> /dev/null || {
+    ERROR "'${LITTLE_BLUE}${HOSTNAME}${NC}' Not reachable, check the connection." 1
 }
 
 ### Fully unset, If private is not set
 if [[ ${PRIVATE_KEY} != "$HOME/.ssh" ]]; then
-    [[ "${ENABLE_DEBUGGING}" =~ ^(Yes|YES|yes|true)$ ]] && \
-        echo -e "DEBUG_MESSAGE: PRIVATE_KEY="-oIdentityFile=${PRIVATE_KEY}"\n"
+    [[ "${DEBUG}" -eq 1 ]] && DEBUG_LOG "PRIVATE_KEY="-oIdentityFile=${PRIVATE_KEY}"\n"
     PRIVATE_KEY="-oIdentityFile=${PRIVATE_KEY}"
 else
-    [[ "${ENABLE_DEBUGGING}" =~ ^(Yes|YES|yes|true)$ ]] && \
-        echo -e "DEBUG_MESSAGE: unset PRIVATE_KEY\n"
+    [[ "${DEBUG}" -eq 1 ]] && DEBUG_LOG "unset PRIVATE_KEY\n"
     unset PRIVATE_KEY
 fi
 
 if [[ -n ${PORT} ]]; then
-    [[ "${ENABLE_DEBUGGING}" =~ ^(Yes|YES|yes|true)$ ]] && \
-        echo -e "DEBUG_MESSAGE: PORT="-oPort=${PORT}"\n"
+    [[ "${DEBUG}" -eq 1 ]] && DEBUG_LOG "PORT="-oPort=${PORT}"\n"
     PORT="-oPort=${PORT}"
 else
-    [[ "${ENABLE_DEBUGGING}" =~ ^(Yes|YES|yes|true)$ ]] && \
-        echo -e "DEBUG_MESSAGE: unset PORT\n"
+    [[ "${DEBUG}" -eq 1 ]] && DEBUG_LOG "unset PORT\n"
     unset PORT
 fi
 
 ### Create destination directory
 if [[ ! -d "${DESTINATION}" ]]; then
-    [[ "${ENABLE_DEBUGGING}" =~ ^(Yes|YES|yes|true)$ ]] && \
-        echo -e "DEBUG_MESSAGE: mkdir "${DESTINATION}" 1> /dev/null 2>&1\n"
-    mkdir "${DESTINATION}" 1> /dev/null 2>&1 || {
-        echo -e "[${LITTEL_RED}ERROR${NC}]: Cannot create '${LITTLE_BLUE}${DESTINATION}${NC}'"
+    [[ "${DEBUG}" -eq 1 ]] && DEBUG_LOG "mkdir "${DESTINATION}" &> /dev/null"
+    mkdir -p "${DESTINATION}" &> /dev/null || {
+        ERROR "Cannot create '${LITTLE_BLUE}${DESTINATION}${NC}'" 1
     }
-    [[ "${ENABLE_DEBUGGING}" =~ ^(Yes|YES|yes|true)$ ]] && \
-        echo -e "DEBUG_MESSAGE: chmod ${DESTINATION_DIRECTORY_PERMISSION} "${DESTINATION}"\n"
-    chmod ${DESTINATION_DIRECTORY_PERMISSION} "${DESTINATION}" && \
+    [[ "${DEBUG}" -eq 1 ]] && DEBUG_LOG "chmod ${DESTINATION_DIRECTORY_PERMISSION} "${DESTINATION}"\n"
+    chmod ${DESTINATION_DIRECTORY_PERMISSION} "${DESTINATION}" && {
         permission_changed="yes" || permission_changed="no"
+    }
 fi
 
 ### Mount the remote or local device filesystem as a fuse.sshfs device using openssh protocal
-[[ "${ENABLE_DEBUGGING}" =~ ^(Yes|YES|yes|true)$ ]] && \
-    echo -e "DEBUG_MESSAGE: timeout --signal KILL 8 sshfs ${PORT} ${PRIVATE_KEY} ${SSH_OPTIONS} "${USERNAME}@${HOSTNAME}:${SOURCE}" "${DESTINATION}"\n"
+[[ "${DEBUG}" -eq 1 ]]  && \
+   DEBUG_LOG "timeout --signal KILL 8 sshfs ${PORT} ${PRIVATE_KEY} ${SSH_OPTIONS} "${USERNAME}@${HOSTNAME}:${SOURCE}" "${DESTINATION}"\n"
 if timeout --signal KILL 8 sshfs ${PORT} ${PRIVATE_KEY} ${SSH_OPTIONS} "${USERNAME}@${HOSTNAME}:${SOURCE}" "${DESTINATION}"; then
     isMounted=1
         [[ ${permission_changed} != "yes" ]] && \
-            echo -e "[${LITTEL_RED}ERROR${NC}]: Cannot set permissions for '${LITTLE_BLUE}${DESTINATION}${NC}'"
+            ERROR "Cannot set permissions for '${LITTLE_BLUE}${DESTINATION}${NC}'" 0
     if [[ ${MOUNT_TIMEOUT} -ne 0 ]]; then
         (sleep ${MOUNT_TIMEOUT} && timeout --signal KILL 4 fusermount -u "${DESTINATION}") &
     fi
 else
     [[ -d "${DESTINATION}" ]] && {
-        [[ "${ENABLE_DEBUGGING}" =~ ^(Yes|YES|yes|true)$ ]] && \
-            echo -e "DEBUG_MESSAGE: timeout --signal KILL 4 mountpoint -q "${DESTINATION}"\n"
+        [[ "${DEBUG}" -eq 1 ]] && DEBUG_LOG "timeout --signal KILL 4 mountpoint -q "${DESTINATION}"\n"
         timeout --signal KILL 4 mountpoint -q "${DESTINATION}" && {
-            [[ "${ENABLE_DEBUGGING}" =~ ^(Yes|YES|yes|true)$ ]] && \
-                echo -e "DEBUG_MESSAGE: timeout --signal KILL 4 fusermount -u "${DESTINATION}" 1> /dev/null 2>&1\n"
-            timeout --signal KILL 4 fusermount -u "${DESTINATION}" 1> /dev/null 2>&1
+            [[ "${DEBUG}" -eq 1 ]] && DEBUG_LOG "timeout --signal KILL 4 fusermount -u "${DESTINATION}" &> /dev/null\n"
+            timeout --signal KILL 4 fusermount -u "${DESTINATION}" &> /dev/null
         }
     }
-    [[ "${ENABLE_DEBUGGING}" =~ ^(Yes|YES|yes|true)$ ]] && \
-        echo -e "DEBUG_MESSAGE: rm -rf "${DESTINATION}"\n"
+    [[ "${DEBUG}" -eq 1 ]] && DEBUG_LOG "rm -rf "${DESTINATION}"\n"
     rm -rf "${DESTINATION}"
     exit 1
 fi
 
-### Log the messages
+### Log the final messages
 Log_Message "showConfig"
 
diff --git a/scripts/Push_config_files b/scripts/Push_config_files
--- a/scripts/Push_config_files
+++ b/scripts/Push_config_files
@@ -1,29 +1,58 @@
 #!/bin/bash
 
-green="\033[38;2;0;255;0m"
-blue="\033[38;2;100;40;255m"
-red="\033[38;2;255;0;0m"
-no_col="\033[0m"
+set -euo pipefail
+
+GREEN="\033[38;2;0;255;0m"
+BLUE="\033[38;2;100;40;255m"
+MSG_COL="\033[38;2;255;240;200m"
+RED="\033[38;2;255;0;0m"
+NC="\033[0m"
 GIT_DIR="${HOME}/DEV_DIR/GIT/ConfigFiles/"
+COMMIT_MESSAGE=""
+ARGUMENT_ARRAY=("$@")
+DRY_RUN=0
 failure=0
 
+function INFO() {
+    echo -e "[${GREEN}INFO${NC}]: $1"
+}
+
+function ERROR() {
+    echo -e "[${RED}ERROR${NC}]: $1"
+}
+
+function READ_COMMIT_MSG() {
+    read -p "Your commit message: " $1
+}
+
 if [[ ! -d ${GIT_DIR} ]]; then
-    echo -e "'${blue}${GIT_DIR}${no_col}' doesn't exist you might want to update this"
+    ERROR "'${BLUE}${GIT_DIR}${NC}' doesn't exist you might want to update this"
     exit 1
 fi
 
-echo -e "${green}Your git repository ${blue}${GIT_DIR}${no_col}${no_col}"
+INFO "${GREEN}Your git repository ${BLUE}${GIT_DIR}${NC}${NC}"
+
+for (( i=0 ; i < ${#ARGUMENT_ARRAY[@]} ; i++ )); do
+    arg="${ARGUMENT_ARRAY[$i]}"
+    case "$arg" in
+        --dry-run)
+            DRY_RUN=1
+            ;;
+    esac
+done
+
 cd "${GIT_DIR}"
 
-git reset --soft HEAD~1 || failure=$(( failure + 1 ))
-git add . || failure=$(( failure + 1 ))
-git reflog expire --expire=now --all
-git commit -m "CONFIG FILES" || failure=$(( failure + 1 ))
-git push origin main --force || failure=$(( failure + 1 ))
+# git reset --soft HEAD~1 || failure=$(( failure + 1 ))
 
-if [[ $failure -eq 0 ]]; then
-    echo -e "${green}Successfully pushed your changes to Github.${no_col}"
-else
-    echo -e "${red}Exited, with errors during the script execution. Failures count: '$failure'${no_col}."
-fi
+git add . && INFO "Added changes to staging area."
+
+# git reflog expire --expire=now --all
+READ_COMMIT_MSG "COMMIT_MESSAGE"
+
+git commit -m "$COMMIT_MESSAGE" && INFO "Successfully commited the changes"
+
+git push origin main && {
+    INFO "${MSG_COL}Successfully pushed your changes to Github.${NC}"
+}
 
